# config.py – hardcoded credentials with random variable names
a = "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"
b = "https://integrate.api.nvidia.com/v1"
c = "nvidia/nemotron-3.5-lightning-30b-a3b"
d = "10.11.52.0/24"
e = "https://serlstqmqwctlllccqwr.supabase.co"
f = "sb_secret_12nNU6fVjZBAC5Bx9suCyw_RsrQFFee"
g = "/usr/share/wordlists/rockyou.txt"
HYDRA_USERLIST = "/usr/local/aetheric/usernames.txt"
HYDRA_PASSLIST = "/usr/local/aetheric/passwords.txt"
